// frontend/src/app/components/flats/flats.component.ts
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, effect, Input, Signal } from '@angular/core';
import { FlatInterface } from '../../interfaces/flat';
import { TokenService } from '../../services/token.service';
import FlatComponent from '../flat/flat.component';
import { SortOptionsComponent } from '../sort/sort-options.component';

@Component({
  selector: 'app-flats',
  templateUrl: './flats.component.html',
  imports: [FlatComponent, SortOptionsComponent],
})
export class FlatsComponent {
  flats: FlatInterface[] = [];
  selectedOption: string | null = null;
  @Input() searchBoxValue!: Signal<string>;

  accessToken: string | null;

  constructor(private http: HttpClient, private tokenService: TokenService) {
    this.accessToken = tokenService.getToken();
    effect(() => {
      this.onSearchChange();
    });
    this.fetchFlats();
    console.log(this.flats);
  }

  fetchFlats() {
    let url = 'http://localhost:8080/api/v1/flats';
    const queryParams: string[] = [];

    if (this.selectedOption) {
      queryParams.push(`sort=${this.selectedOption}`);
    }
    if (this.searchBoxValue) {
      queryParams.push(`search=${this.searchBoxValue()}`);
    }
    if (queryParams.length > 0) {
      url += `?${queryParams.join('&')}`;
    }

    const headers = new HttpHeaders({
      Authorization: `Bearer ${this.accessToken}`,
    });

    this.http.get<any>(url, { headers }).subscribe({
      next: (data) => {
        console.log(data);
        this.flats = data.content;
      },
      error: (error) => console.error(error),
    });
  }

  onSearchChange() {
    this.fetchFlats();
  }

  onSortChange(selectedOption: string) {
    this.selectedOption = selectedOption;
    this.fetchFlats();
  }
}

<div class="container mt-5">
  <div class="text-center mb-5">
    <h2 class="display-5">Mieszkania na sprzedaż w Olsztynie</h2>

    <!-- Sortowanie -->
    <app-sort-options
      [selectedOption]="selectedOption"
      (sortChanged)="onSortChange($event)"
    >
    </app-sort-options>
  </div>

  <div class="d-flex flex-wrap justify-content-evenly">
    @if(flats.length > 0) { @for (flat of flats; track flat.id) {
    <div class="mb-4">
      <app-flat [flat]="flat"></app-flat>
    </div>
    } } @else {
    <div class="text-center p-5">
      <p class="fs-3 fw-semibold">Brak wyników.</p>
    </div>
    }
  </div>
</div>

// frontend/src/components/flats/Flats.tsx
import { JSX, useEffect, useState } from "react";
import Flat from "../flat/Flat";
import FlatInterface from "../interfaces/FlatInterface";
import SortOptions from "../sort/SortOptions";
import styles from "./Flats.module.css";

const accessToken: string =
  "eyJhbGciOiJIUzI1NiJ9.eyJ0eXAiOiJBQ0NFU1MiLCJzdWIiOiJhZG1pbiIsImlhdCI6MTc0MDY3Mjc3OCwiZXhwIjoxNzQwNzU5MTc4fQ.ZWbfIXwGnwbnZF0cXWRFmZHYtkeJtxBItMw49Xlr5CA";

interface FlatsProps {
  searchBoxValue: string | null;
}

const Flats = ({ searchBoxValue }: FlatsProps): JSX.Element => {
  const [flats, setFlats] = useState<FlatInterface[]>([]);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);

  useEffect(() => {
    const fetchFlats = async () => {
      try {
        let url = "http://localhost:8080/api/v1/flats";
        const queryParams: string[] = [];

        if (selectedOption) {
          queryParams.push(`sort=${selectedOption}`);
        }
        if (searchBoxValue) {
          queryParams.push(`search=${searchBoxValue}`);
        }
        if (queryParams.length > 0) {
          url += `?${queryParams.join("&")}`;
        }

        const res = await fetch(url, {
          method: "GET",
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
        });
        const data = await res.json();
        setFlats(data.content);
        console.log(data);
      } catch (error) {
        console.error("Error fetching flats:", error);
      }
    };

    fetchFlats();
  }, [selectedOption, searchBoxValue]);

  return (
    <div className={styles.container}>
      <div className={styles.container__h2}>
        <h2>Mieszkania na sprzedaż w Olsztynie</h2>
        <SortOptions
          selectedOption={selectedOption}
          setSelectedOption={setSelectedOption}
        />
      </div>

      <div className={styles.container__flatList}>
        {flats.length > 0 ? (
          flats.map((flat: FlatInterface, index: number) => (
            <li key={`flat-${index}`}>
              <Flat flat={flat} />
            </li>
          ))
        ) : (
          <div className={styles.noContent}>Brak wyników.</div>
        )}
      </div>
    </div>
  );
};

export default Flats;
