// frontend/src/components/flat/Flat.tsx
import "boxicons/css/boxicons.min.css";
import { JSX } from "react";
import FlatInterface from "../interfaces/FlatInterface";
import styles from "./Flat.module.css";

interface FlatProps {
  flat: FlatInterface;
}

const Flat = ({ flat }: FlatProps): JSX.Element => {
  return (
    <div className={styles.flatContainer}>
      <div className={styles.image}>
        <img src={flat.imageUrl} alt="flat image" />
      </div>
      <div className={styles.details}>
        <h2>{flat.price.toLocaleString()} zł</h2>
        <h3>{flat.pricePerMeter.toLocaleString()} zł/m&sup2;</h3>
        <div className={styles.address}>
          <i className="bx bx-map"></i>
          <a
            href={`https://www.google.com/maps/search/?q=${encodeURIComponent(
              flat.address
            )}`}
            target="_blank"
          >
            {flat.address}
          </a>
        </div>
        <div className={styles.area}>
          <i className="bx bx-area"></i>
          <span>{flat.area} m&sup2;</span>
        </div>
        <div className={styles.rooms}>
          <i className="bx bx-door-open"></i>
          <span>{flat.rooms} pokoje</span>
        </div>
        <div className={styles.floor}>
          <i className="bx bx-building"></i>
          <span>{flat.floor > 0 ? `${flat.floor} piętro` : "parter"}</span>
        </div>
      </div>
    </div>
  );
};

export default Flat;

// frontend/src/app/components/flat/flat.component.ts
import { DecimalPipe } from '@angular/common';
import { Component, Input } from '@angular/core';
import { FlatInterface } from '../../interfaces/flat';

@Component({
  selector: 'app-flat',
  templateUrl: './flat.component.html',
  styleUrls: ['./flat.component.css'],
  imports: [DecimalPipe],
})
export default class FlatComponent {
  @Input() flat!: FlatInterface;
}

<div class="card equal-height-card h-100" style="width: 25rem">
  <img [src]="flat.imageUrl" class="card-img-top flat-img" alt="flat image" />

  <div class="card-body">
    <h5 class="card-title fs-3">{{ flat.price | number : "1.0-0" }} zł</h5>
    <h6 class="card-subtitle mb-3 text-muted fs-5">
      {{ flat.pricePerMeter | number : "1.0-0" }} zł/m²
    </h6>

    <p class="card-text d-flex align-items-center mb-2">
      <i class="bx bx-map me-2 fs-3"></i>
      <a
        [href]="'https://www.google.com/maps/search/?q=' + flat.address"
        target="_blank"
        class="text-decoration-none text-dark"
      >
        {{ flat.address }}
      </a>
    </p>

    <p class="card-text d-flex align-items-center mb-2">
      <i class="bx bx-area me-2 fs-3"></i>
      {{ flat.area }} m²
    </p>

    <p class="card-text d-flex align-items-center mb-2">
      <i class="bx bx-door-open me-2 fs-3"></i>
      {{ flat.rooms }} pokoje
    </p>

    <p class="card-text d-flex align-items-center">
      <i class="bx bx-building me-2 fs-3"></i>
      {{ flat.floor > 0 ? flat.floor + " piętro" : "parter" }}
    </p>
  </div>
</div>
